# Generated by Django 4.1.1 on 2022-09-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tradehelper", "0002_remove_subscription_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        help_text="Статус заказа", max_length=50, null=True
                    ),
                ),
                ("payment_id", models.IntegerField(null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Стоимость заказа",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "payment_url",
                    models.CharField(
                        help_text="Ссылка на оплату", max_length=500, null=True
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
