# Generated by Django 4.1.1 on 2022-09-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehelper', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='rebill_id',
            field=models.IntegerField(null=True),
        ),
    ]
