# Generated by Django 4.1.1 on 2022-09-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tradehelper", "0006_subscription_rebill_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="rebill_id",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
