# Generated by Django 4.1.1 on 2022-09-28 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tradehelper", "0007_alter_subscription_rebill_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tradehelper.subscription",
            ),
        ),
    ]
