// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: b7qxVGc4J2aoxUpARxxPVV
// Component: tKVfRngsljsxH
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: P3BswEn_gt1WP/component
import Button from "../../Button"; // plasmic-import: BBnBngbU-SWcU/component
import Section from "../../Section"; // plasmic-import: mkuY5Znd7ymWD/component
import DiagramCard from "../../DiagramCard"; // plasmic-import: s_4mE5zkCqOBb/component
import ProductCard from "../../ProductCard"; // plasmic-import: oCiv5DT4-5-aG/component
import DetailAbout from "../../DetailAbout"; // plasmic-import: YeffN91NRPGh2/component
import PriceSection from "../../PriceSection"; // plasmic-import: 67Bru7ubRGemv/component
import PriceCard from "../../PriceCard"; // plasmic-import: Mt936vgmlbhfCw/component
import FooterSection from "../../FooterSection"; // plasmic-import: YLg_xYY5lZJcMe/component

import { useScreenVariants as useScreenVariantsbfAeazZolEhus } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: BfAeazZolEHUS/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_dark_saa_s_landing_page.module.css"; // plasmic-import: b7qxVGc4J2aoxUpARxxPVV/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: tKVfRngsljsxH/css

import IconArrowRightsvgIcon from "./icons/PlasmicIcon__IconArrowRightsvg"; // plasmic-import: ux7ZMjlfao5rQ/icon

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  headerHeroSection?: p.Flex<"div">;
  navbar?: p.Flex<typeof Navbar>;
  h1?: p.Flex<"h1">;
  diagramSection?: p.Flex<typeof Section>;
  deviceSection?: p.Flex<typeof Section>;
  gallerySection?: p.Flex<typeof Section>;
  productSection?: p.Flex<typeof Section>;
  aboutSection?: p.Flex<typeof Section>;
  priceSection?: p.Flex<typeof PriceSection>;
  startSection?: p.Flex<typeof Section>;
  h3?: p.Flex<"h3">;
  pricingSection?: p.Flex<typeof Section>;
  footerSection?: p.Flex<typeof FooterSection>;
};

export interface DefaultHomepageProps {}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbfAeazZolEhus()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        {(hasVariant(globalVariants, "screen", "mobileOnly") ? true : true) ? (
          <div
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              projectcss.plasmic_tokens,
              sty.root
            )}
          >
            {true ? (
              <p.Stack
                as={"div"}
                data-plasmic-name={"headerHeroSection"}
                data-plasmic-override={overrides.headerHeroSection}
                hasGap={true}
                className={classNames(projectcss.all, sty.headerHeroSection)}
              >
                {true ? (
                  <Navbar
                    data-plasmic-name={"navbar"}
                    data-plasmic-override={overrides.navbar}
                    className={classNames("__wab_instance", sty.navbar)}
                  />
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__gqb95)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__uueIa)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mbI49)}
                    >
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Analytics for developers can be better"
                          : "Analytics for \ndevelopers can\nbe better"}
                      </h1>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tvDzk
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                          : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."}
                      </div>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__fTw5L
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__gj0Cd
                          )}
                          color={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? ("blueSmall" as const)
                              : ("blue" as const)
                          }
                          endIcon={
                            (
                              hasVariant(globalVariants, "screen", "mobileOnly")
                                ? true
                                : true
                            ) ? (
                              <IconArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__qtIgz
                                )}
                                role={"img"}
                              />
                            ) : null
                          }
                          link={"#" as const}
                          showEndIcon={true}
                          startIcon={
                            <svg
                              className={classNames(
                                projectcss.all,
                                sty.svg___2SvEl
                              )}
                              role={"img"}
                            />
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___8Feiw
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Try Demo For Free"
                              : "Try Demo For Free"}
                          </div>
                        </Button>

                        {(
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? true
                            : true
                        ) ? (
                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__gMKuy
                            )}
                            color={
                              hasVariant(globalVariants, "screen", "mobileOnly")
                                ? ("blueBorderSmall" as const)
                                : ("blueBorder" as const)
                            }
                            endIcon={
                              <svg
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__peiwp
                                )}
                                role={"img"}
                              />
                            }
                            link={"#" as const}
                            startIcon={
                              <svg
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__mhDRn
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__rv9F7
                              )}
                            >
                              {hasVariant(
                                globalVariants,
                                "screen",
                                "mobileOnly"
                              )
                                ? "Learn More"
                                : "Learn More"}
                            </div>
                          </Button>
                        ) : null}
                      </p.Stack>

                      {(
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : false
                      ) ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__xHqj
                          )}
                        >
                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__bMstC
                            )}
                            color={"blueBorder" as const}
                            endIcon={
                              <svg
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ezyM0
                                )}
                                role={"img"}
                              />
                            }
                            startIcon={
                              <svg
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ilGaJ
                                )}
                                role={"img"}
                              />
                            }
                          >
                            {"Learn More"}
                          </Button>

                          {(
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? true
                              : true
                          ) ? (
                            <Button
                              className={classNames(
                                "__wab_instance",
                                sty.button__oYu0W
                              )}
                              color={"blueBorder" as const}
                              endIcon={
                                <svg
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__yz7
                                  )}
                                  role={"img"}
                                />
                              }
                              startIcon={
                                <svg
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg___4Ripy
                                  )}
                                  role={"img"}
                                />
                              }
                            >
                              {"Learn More"}
                            </Button>
                          ) : null}
                        </div>
                      ) : null}
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__v5FsM)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__v2Hcg)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? ("0px" as const)
                            : ("661px" as const)
                        }
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? ("100%" as const)
                            : ("100%" as const)
                        }
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/dark_saa_s_landing_page/images/diagramsvg.svg",
                          fullWidth: 173,
                          fullHeight: 150,
                          aspectRatio: 1.151631
                        }}
                      />
                    </div>
                  </p.Stack>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eKHh
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Powering with magnificant of Companies"
                      : "Powering with magnificant of Companies"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__igoFn)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__rXckL)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? ("170px" as const)
                          : ("100%" as const)
                      }
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/dark_saa_s_landing_page/images/logoHero1Png.png",
                        fullWidth: 233,
                        fullHeight: 50,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__aRiSu)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? ("170px" as const)
                          : ("100%" as const)
                      }
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/dark_saa_s_landing_page/images/logoHero2Png.png",
                        fullWidth: 189,
                        fullHeight: 50,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___6Dc)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? ("170px" as const)
                          : ("100%" as const)
                      }
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/dark_saa_s_landing_page/images/logoHero3Png.png",
                        fullWidth: 194,
                        fullHeight: 50,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___9XpxR)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? ("170px" as const)
                          : ("100%" as const)
                      }
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/dark_saa_s_landing_page/images/logoHero4Png.png",
                        fullWidth: 189,
                        fullHeight: 50,
                        aspectRatio: undefined
                      }}
                    />
                  </p.Stack>
                </div>
              </p.Stack>
            ) : null}

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__qbRlI)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/dark_saa_s_landing_page/images/diagramImgsvg.svg",
                fullWidth: 300,
                fullHeight: 100,
                aspectRatio: 2.987552
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__uzClH)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"774px" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/dark_saa_s_landing_page/images/ellipseLeftpng.png",
                fullWidth: 469,
                fullHeight: 742,
                aspectRatio: undefined
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__sRhR3)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/dark_saa_s_landing_page/images/ellipseRightpng.png",
                fullWidth: 437,
                fullHeight: 742,
                aspectRatio: undefined
              }}
            />

            <Section
              data-plasmic-name={"diagramSection"}
              data-plasmic-override={overrides.diagramSection}
              className={classNames("__wab_instance", sty.diagramSection)}
              size={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("mobile" as const)
                  : undefined
              }
            >
              <div className={classNames(projectcss.all, sty.freeBox__ezwPh)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___1N5ZQ
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "Lorem ipsum dolor \nsit amet"
                    : "Lorem ipsum dolor \nsit amet"}
                </h2>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mHRrd
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__wXfX0)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? ("249px" as const)
                      : ("100%" as const)
                  }
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/dark_saa_s_landing_page/images/terminalpng.png",
                    fullWidth: 624,
                    fullHeight: 333,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__pn9Xx)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? ("auto" as const)
                      : ("auto" as const)
                  }
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/dark_saa_s_landing_page/images/line1Png.png",
                    fullWidth: 11,
                    fullHeight: 150,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__dDQel)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? ("50px" as const)
                      : ("100%" as const)
                  }
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/dark_saa_s_landing_page/images/lineBranchpng.png",
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___3RBKk)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? ("auto" as const)
                      : ("auto" as const)
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? ("500px" as const)
                      : ("770px" as const)
                  }
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? ("auto" as const)
                      : ("auto" as const)
                  }
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/dark_saa_s_landing_page/images/line2Png.png",
                    fullWidth: 844,
                    fullHeight: 284,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__rsMjm)}
                >
                  <DiagramCard
                    className={classNames(
                      "__wab_instance",
                      sty.diagramCard__gy1QN
                    )}
                  />

                  <DiagramCard
                    className={classNames(
                      "__wab_instance",
                      sty.diagramCard__gVtTn
                    )}
                  />

                  <DiagramCard
                    className={classNames(
                      "__wab_instance",
                      sty.diagramCard__dWDe
                    )}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__nrlMs)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__z9Zg)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("72px" as const)
                        : ("none" as const)
                    }
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("72px" as const)
                        : ("100%" as const)
                    }
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/dark_saa_s_landing_page/images/dollarpng.png",
                      fullWidth: 100,
                      fullHeight: 100,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___6UcMz)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("72px" as const)
                        : ("none" as const)
                    }
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("72px" as const)
                        : ("100%" as const)
                    }
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/dark_saa_s_landing_page/images/messagepng.png",
                      fullWidth: 100,
                      fullHeight: 100,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__nKdo5)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("72px" as const)
                        : ("none" as const)
                    }
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("72px" as const)
                        : ("100%" as const)
                    }
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/dark_saa_s_landing_page/images/importpng.png",
                      fullWidth: 100,
                      fullHeight: 100,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__yrtEq)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("72px" as const)
                        : ("none" as const)
                    }
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("72px" as const)
                        : ("100%" as const)
                    }
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/dark_saa_s_landing_page/images/lineBranchpng.png",
                      fullWidth: 100,
                      fullHeight: 100,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ixL1)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("72px" as const)
                        : ("none" as const)
                    }
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("72px" as const)
                        : ("100%" as const)
                    }
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/dark_saa_s_landing_page/images/exportpng.png",
                      fullWidth: 100,
                      fullHeight: 100,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__m3DDq)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("72px" as const)
                        : ("none" as const)
                    }
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("72px" as const)
                        : ("100%" as const)
                    }
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/dark_saa_s_landing_page/images/message2Png.png",
                      fullWidth: 100,
                      fullHeight: 100,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__zH19X)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("72px" as const)
                        : ("none" as const)
                    }
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("72px" as const)
                        : ("100%" as const)
                    }
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/dark_saa_s_landing_page/images/message3Png.png",
                      fullWidth: 100,
                      fullHeight: 100,
                      aspectRatio: undefined
                    }}
                  />
                </p.Stack>

                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___47O7E
                  )}
                >
                  {"Lorem ipsum dolor \nsit amet"}
                </h2>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pkdYo
                  )}
                >
                  {
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                  }
                </div>
              </div>
            </Section>

            <Section
              data-plasmic-name={"deviceSection"}
              data-plasmic-override={overrides.deviceSection}
              background={"dark" as const}
              className={classNames("__wab_instance", sty.deviceSection)}
              size={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("mobile" as const)
                  : undefined
              }
            >
              <div className={classNames(projectcss.all, sty.freeBox__foHmx)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__wyRAd
                  )}
                >
                  {"Lorem ipsum dolor sit amet"}
                </h2>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__m6ZNc
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do \neiusmod tempor incididunt ut labore et dolore magna aliqua."
                    : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do \neiusmod tempor incididunt ut labore et dolore magna aliqua."}
                </div>
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___4XPJm)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("360px" as const)
                    : ("100%" as const)
                }
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/dark_saa_s_landing_page/images/macbookpng.png",
                  fullWidth: 900,
                  fullHeight: 565,
                  aspectRatio: undefined
                }}
              />
            </Section>

            <Section
              data-plasmic-name={"gallerySection"}
              data-plasmic-override={overrides.gallerySection}
              className={classNames("__wab_instance", sty.gallerySection)}
              size={"fullContentGallery" as const}
            >
              <div className={classNames(projectcss.all, sty.freeBox__girJ)}>
                <div className={classNames(projectcss.all, sty.columns__klblT)}>
                  <div
                    className={classNames(projectcss.all, sty.column__wBk3G)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__rIjmi)}
                      displayHeight={"100%" as const}
                      displayMaxHeight={"300px" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/dark_saa_s_landing_page/images/galleri11Png.png",
                        fullWidth: 700,
                        fullHeight: 300,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__hqn6T)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__cpr0F)}
                      displayHeight={"100%" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/dark_saa_s_landing_page/images/galleri12Png.png",
                        fullWidth: 700,
                        fullHeight: 300,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__vr2MU)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__k8YVy)}
                      displayHeight={"100%" as const}
                      displayMaxHeight={"300px" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/dark_saa_s_landing_page/images/galleri13Png.png",
                        fullWidth: 700,
                        fullHeight: 300,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.columns__o6G2E)}>
                  <div
                    className={classNames(projectcss.all, sty.column__cH8LH)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__hPwJ)}
                      displayHeight={"100%" as const}
                      displayMaxHeight={"300px" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/dark_saa_s_landing_page/images/galleri21Png.png",
                        fullWidth: 700,
                        fullHeight: 300,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__pbhgX)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__kFobf)}
                      displayHeight={"100%" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/dark_saa_s_landing_page/images/galleri22Png.png",
                        fullWidth: 700,
                        fullHeight: 300,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__nVnW7)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__scvF1)}
                      displayHeight={"100%" as const}
                      displayMaxHeight={"300px" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/dark_saa_s_landing_page/images/galleri23Png.png",
                        fullWidth: 700,
                        fullHeight: 300,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
              </div>
            </Section>

            <Section
              data-plasmic-name={"productSection"}
              data-plasmic-override={overrides.productSection}
              className={classNames("__wab_instance", sty.productSection)}
              size={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("mobile" as const)
                  : undefined
              }
            >
              <div className={classNames(projectcss.all, sty.freeBox__obiO4)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__kNknI
                  )}
                >
                  {"Lorem ipsum dolor sit amet"}
                </h2>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hpTm
                  )}
                >
                  {
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do \neiusmod tempor incididunt ut labore et dolore magna aliqua."
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__muYel)}
                  color={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? ("blue" as const)
                      : ("blue" as const)
                  }
                  endIcon={
                    <svg
                      className={classNames(projectcss.all, sty.svg__f2I)}
                      role={"img"}
                    />
                  }
                  link={"#" as const}
                  startIcon={
                    <svg
                      className={classNames(projectcss.all, sty.svg__zL6Ot)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d3CRn
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Get Started"
                      : "Get Started"}
                  </div>
                </Button>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__aoCua)}
                >
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__aXjJ2
                    )}
                  />

                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__gBoj5
                    )}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__nqpe3)}
                >
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__t6VzH
                    )}
                  />

                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__yXlv
                    )}
                  />
                </p.Stack>
              </div>
            </Section>

            <Section
              data-plasmic-name={"aboutSection"}
              data-plasmic-override={overrides.aboutSection}
              background={"dark" as const}
              className={classNames("__wab_instance", sty.aboutSection)}
              size={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? ("mobile" as const)
                  : undefined
              }
            >
              <div className={classNames(projectcss.all, sty.freeBox__vDiVx)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__gyAlz
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "What people say \nabout us"
                    : "What people say about us"}
                </h2>

                <div className={classNames(projectcss.all, sty.freeBox__rfsPx)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__kjd5G)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__nZbLh)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? ("339px" as const)
                          : ("100%" as const)
                      }
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/dark_saa_s_landing_page/images/aboutImgpng.png",
                        fullWidth: 400,
                        fullHeight: 500,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__fS9Tr)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__cahBj
                      )}
                    >
                      {"Michael Justin"}
                    </h2>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__wEtbY)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__tszV4)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/dark_saa_s_landing_page/images/aboutIpsumpng.png",
                          fullWidth: 152,
                          fullHeight: 40,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xeVau
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CEO Company"
                          : "CEO Company"}
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__lri1E)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__me4Ud)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? ("auto" as const)
                            : ("auto" as const)
                        }
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/dark_saa_s_landing_page/images/backtippng.png",
                          fullWidth: 34,
                          fullHeight: 32,
                          aspectRatio: undefined
                        }}
                      />
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9UsPy
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                        : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."}
                    </div>
                  </div>
                </div>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__y5XGz)}
                >
                  <DetailAbout
                    className={classNames(
                      "__wab_instance",
                      sty.detailAbout__tBdt
                    )}
                  />

                  <DetailAbout
                    className={classNames(
                      "__wab_instance",
                      sty.detailAbout__jsk7L
                    )}
                  />

                  <DetailAbout
                    className={classNames(
                      "__wab_instance",
                      sty.detailAbout__xXziW
                    )}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___8Q2Pr)}
                >
                  <DetailAbout
                    className={classNames(
                      "__wab_instance",
                      sty.detailAbout__r2Pz0
                    )}
                  />

                  <DetailAbout
                    className={classNames(
                      "__wab_instance",
                      sty.detailAbout__w3C0P
                    )}
                  />

                  <DetailAbout
                    className={classNames(
                      "__wab_instance",
                      sty.detailAbout__q2OTw
                    )}
                  />
                </p.Stack>

                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__i7Vnq)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/dark_saa_s_landing_page/images/arrowLeftpng.png",
                      fullWidth: 24,
                      fullHeight: 24,
                      aspectRatio: undefined
                    }}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__omYu5)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/dark_saa_s_landing_page/images/arrowRightpng2.png",
                      fullWidth: 24,
                      fullHeight: 24,
                      aspectRatio: undefined
                    }}
                  />
                ) : null}
              </div>
            </Section>

            {true ? (
              <PriceSection
                data-plasmic-name={"priceSection"}
                data-plasmic-override={overrides.priceSection}
                className={classNames("__wab_instance", sty.priceSection)}
              />
            ) : null}

            <Section
              data-plasmic-name={"startSection"}
              data-plasmic-override={overrides.startSection}
              className={classNames("__wab_instance", sty.startSection)}
              size={"fullContentWidth" as const}
            >
              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__omfzC)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__wTIgl)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/dark_saa_s_landing_page/images/pricingImgsvg.svg",
                      fullWidth: 300,
                      fullHeight: 67,
                      aspectRatio: 4.468401
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.columns__nJuGy)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___49IA)}
                    >
                      <h3
                        data-plasmic-name={"h3"}
                        data-plasmic-override={overrides.h3}
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Start using our product today"
                          : "Start using our product today"}
                      </h3>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2Z5L8
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Faster than free analytics tools. Access to all your data, with respect to the privacy of your users."
                          : "Faster than free analytics tools. Access to all your data, with respect to the privacy of your users."}
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column___7Dcdz)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__b3WmR
                        )}
                        color={"white" as const}
                        endIcon={
                          <svg
                            className={classNames(
                              projectcss.all,
                              sty.svg___06Ox9
                            )}
                            role={"img"}
                          />
                        }
                        link={"#" as const}
                        startIcon={
                          <svg
                            className={classNames(
                              projectcss.all,
                              sty.svg__hIw0S
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___2TlJp
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "Get Started"
                            : "Get Started"}
                        </div>
                      </Button>
                    </div>
                  </div>
                </div>
              ) : null}
            </Section>

            {true ? (
              <Section
                data-plasmic-name={"pricingSection"}
                data-plasmic-override={overrides.pricingSection}
                className={classNames("__wab_instance", sty.pricingSection)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__x0ZVw)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__ys2U5)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__zeUm)}
                    >
                      <PriceCard
                        borders={["flatLeft"]}
                        className={classNames(
                          "__wab_instance",
                          sty.priceCard__pnEjp
                        )}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__ibHlL)}
                    >
                      <PriceCard
                        borders={["flatCenter"]}
                        className={classNames(
                          "__wab_instance",
                          sty.priceCard__ijivO
                        )}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___9PG61
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___6GjFp
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "We Recommended"
                              : "We Recommended"}
                          </div>
                        </div>
                      ) : null}
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__glPpd)}
                    >
                      <PriceCard
                        borders={["flatRight"]}
                        className={classNames(
                          "__wab_instance",
                          sty.priceCard__fZptz
                        )}
                      />
                    </div>
                  </p.Stack>
                </div>
              </Section>
            ) : null}
            {true ? (
              <FooterSection
                data-plasmic-name={"footerSection"}
                data-plasmic-override={overrides.footerSection}
                className={classNames("__wab_instance", sty.footerSection)}
              />
            ) : null}
          </div>
        ) : null}
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerHeroSection",
    "navbar",
    "h1",
    "diagramSection",
    "deviceSection",
    "gallerySection",
    "productSection",
    "aboutSection",
    "priceSection",
    "startSection",
    "h3",
    "pricingSection",
    "footerSection"
  ],
  headerHeroSection: ["headerHeroSection", "navbar", "h1"],
  navbar: ["navbar"],
  h1: ["h1"],
  diagramSection: ["diagramSection"],
  deviceSection: ["deviceSection"],
  gallerySection: ["gallerySection"],
  productSection: ["productSection"],
  aboutSection: ["aboutSection"],
  priceSection: ["priceSection"],
  startSection: ["startSection", "h3"],
  h3: ["h3"],
  pricingSection: ["pricingSection"],
  footerSection: ["footerSection"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerHeroSection: "div";
  navbar: typeof Navbar;
  h1: "h1";
  diagramSection: typeof Section;
  deviceSection: typeof Section;
  gallerySection: typeof Section;
  productSection: typeof Section;
  aboutSection: typeof Section;
  priceSection: typeof PriceSection;
  startSection: typeof Section;
  h3: "h3";
  pricingSection: typeof Section;
  footerSection: typeof FooterSection;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    navbar: makeNodeComponent("navbar"),
    h1: makeNodeComponent("h1"),
    diagramSection: makeNodeComponent("diagramSection"),
    deviceSection: makeNodeComponent("deviceSection"),
    gallerySection: makeNodeComponent("gallerySection"),
    productSection: makeNodeComponent("productSection"),
    aboutSection: makeNodeComponent("aboutSection"),
    priceSection: makeNodeComponent("priceSection"),
    startSection: makeNodeComponent("startSection"),
    h3: makeNodeComponent("h3"),
    pricingSection: makeNodeComponent("pricingSection"),
    footerSection: makeNodeComponent("footerSection"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Home",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
